@echo off
REM start-backend.cmd - Sets environment variables and starts FastAPI
REM This script is generated by verify--gcp-migration.ps1

set GOOGLE_CLOUD_PROJECT=%1
set GCS_BUCKET_NAME=%2
set FIRESTORE_DATABASE_ID=%3
set USE_MOCK_DATA=%4
set USE_FIRESTORE_EMULATOR=%5
set USE_GCS_EMULATOR=%6
set APP_ENV=%7
set GOOGLE_API_KEY=%8
set ELEVENLABS_API_KEY=%9

uv run uvicorn backend.main:app --host localhost --port 8000
